# Generated by Django 5.0.4 on 2024-04-15 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_produt_name_product_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('color', 'Color'), ('size', 'Size')], max_length=100)),
                ('category_value', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('craeted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
