# Generated by Django 5.0.4 on 2024-04-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accounts_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
